// <auto-generated />
using InmobilariaReal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobilariaReal.Migrations
{
    [DbContext(typeof(CasarealContext))]
    [Migration("20220728035935_migracion")]
    partial class migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InmobilariaReal.Models.Categorium", b =>
                {
                    b.Property<int>("Idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcategoria"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre");

                    b.HasKey("Idcategoria")
                        .HasName("PK__Categori__140587C777A0F501");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("InmobilariaReal.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"), 1L, 1);

                    b.Property<int>("CantBano")
                        .HasColumnType("int")
                        .HasColumnName("cant_bano");

                    b.Property<int>("CantPieza")
                        .HasColumnType("int")
                        .HasColumnName("cant_pieza");

                    b.Property<int>("Idcategoria")
                        .HasColumnType("int")
                        .HasColumnName("idcategoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("Precio")
                        .HasColumnType("int")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__FF341C0D3B6E1AF8");

                    b.HasIndex("Idcategoria");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("InmobilariaReal.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdReporte")
                        .HasName("PK__Reporte__87E4F5CB7B12C1E1");

                    b.ToTable("Reporte", (string)null);
                });

            modelBuilder.Entity("InmobilariaReal.Models.Producto", b =>
                {
                    b.HasOne("InmobilariaReal.Models.Categorium", "IdcategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("Idcategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Categoria");

                    b.Navigation("IdcategoriaNavigation");
                });

            modelBuilder.Entity("InmobilariaReal.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
